version: "3.9"
services:
  test-runner:
    image: express-user-management:dev
    networks:
      - express-user-management-unit-tests-net
    entrypoint: [
      "npm",
      "exec",
      "--",
      "jest",
      "--coverage",
      "--runInBand",
      "--testMatch=**/tests/unit-tests/**/*.test.ts"
    ]
    
networks:
  express-user-management-unit-tests-net:
    driver: bridge
    name: express-user-management-unit-tests-net